#!/bin/bash

#Coded by Krypt0N

items=("https://www.youtube.com/watch?v=YnmEePUXLRs" "https://www.youtube.com/watch?v=3vVSBLkpO-8" "https://www.youtube.com/watch?v=iPKJUzkTt6Y")

size=${#items[@]}
randomindex=$(($RANDOM % $size))

echo -e "\e[1;4;35mIf you want to stop playing press (CTRL + C)"

mpv ${items[$randomindex]}

CANCION=${items[$randomindex]}

if [ "$CANCION" == "https://www.youtube.com/watch?v=YnmEePUXLRs" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: The Less i Know the Better - Tame Impala" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo
fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=3vVSBLkpO-8" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Baby Im Yours - Breakbot" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=iPKJUzkTt6Y" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: The Look - Metronomy" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

echo -e "\e[93mDo you wanna listen another song?"
 select yn in "Yes" "No"; do
    case $yn in
        Yes ) bash MRIndie;;

         No ) 
	     echo -e "\e[94mDo you wanna listen another genre?"
             	select yn in "Yes" "No"; do
               		case $yn in
                 		Yes ) bash Test1.sh; exit;;
                 		No ) clear; echo "See you later!" | lolcat -a; exit;;
                 		* ) echo "Please choice a valid option!";;
                   			esac
                                        	done;;	 

	* ) echo "Please choice a valid option!";;
    esac
done



	



