#!/bin/bash

#Coded by Krypt0N

items=("https://www.youtube.com/watch?v=5SXeK9DKprM" "https://www.youtube.com/watch?v=W4DfbinBgL4" "https://www.youtube.com/watch?v=u6LahTuw02c")

size=${#items[@]}
randomindex=$(($RANDOM % $size))

echo -e "\e[1;4;35mIf you want to stop playing press (CTRL + C)"

mpv ${items[$randomindex]}

CANCION=${items[$randomindex]}

if [ "$CANCION" == "https://www.youtube.com/watch?v=5SXeK9DKprM" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Paranoid - Black Sabbath" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo
fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=u6LahTuw02c" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: Master of Puppets - Metallica" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

if [ "$CANCION" == "https://www.youtube.com/watch?v=W4DfbinBgL4" ]
then
	echo 
	 echo -e "\e[91m------------------------------------------------------"
       	echo -e "\e[1mThis was: The Trooper - Iron Maiden" | lolcat
	 echo -e "\e[91m------------------------------------------------------"
         echo

fi

echo -e "\e[93mDo you wanna listen another song?"
 select yn in "Yes" "No"; do
    case $yn in
        Yes ) bash RMetal;;

         No ) 
	     echo -e "\e[94mDo you wanna listen another genre?"
             	select yn in "Yes" "No"; do
               		case $yn in
                 		Yes ) bash Test1.sh; exit;;
                 		No ) clear; echo "See you later!" | lolcat -a; exit;;
                 		* ) echo "Please choice a valid option!";;
                   			esac
                                        	done;;	 

	* ) echo "Please choice a valid option!";;
    esac
done



	



